name: Recent Activity

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@v1.1.1
        with:
          username: sihab143
          max_lines: 5
